# Uncomment the next line to define a global platform for your project
platform :ios, '12.4'

target 'MEMOO' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MEMOO

#pod 'Google-Mobile-Ads-SDK'
pod 'Google-Mobile-Ads-SDK', '~> 7.42.2'
#pod 'Google-Mobile-Ads-SDK', '~> 7.64.0'
end
