
enum ProductIDs: String, CaseIterable {
    case unlockAllContentID = "unlockAllContentID"
    case unlockalfredID     = "unlockAlfredID"
    case unlockanimallID    = "unlockAnimallID"
    case unlockmandalaID    = "unlockMandalaID"
    case unlockninjaID      = "unlockNinjaID"
    case unlocksportID      = "unlockSportID"
    case unlocksummerID     = "unlockSummerID"
    case unlocktoyID        = "unlockToyID"
    case unlockdogID        = "unlockDogID"
    case unlocktoyyID       = "unlockToyyID"
    case unlockvegetableID  = "unlockVegetableID"
    case unlockspaceID      = "unlockSpaceID"
    case unlockletterID     = "unlockLetterID"
    case unlockorigamiID    = "unlockOrigamiID"
    case unlockanimalllID   = "unlockAnimalllID"
    case unlockflowerID     = "unlockFlowerID"
    case unlockfauna        = "unlockFaunaID"
}
